name: flutter_appwrite_starter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  appwrite: ^0.4.0
  crop: ^0.5.0
  device_info_plus: ^1.0.0
  flutter_riverpod: ^0.13.1+1
  flutter_svg: ^0.19.3
  flutter_swiper: ^1.1.6
  google_fonts: ^2.0.0
  image_picker: ^0.7.4
  intl: ^0.17.0
  package_info_plus: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2

dependency_overrides:
  appwrite:
    # path: '/home/dlohani/Documents/projects/appwrite/sdks/sdk-for-flutter'
    git: 
      url: git@github.com:appwrite/sdk-for-flutter.git
      ref: feat-null-safety-new
flutter:
  generate: true
  uses-material-design: true
