name: components

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6

dev_dependencies:
  flutter_lints: ^2.0.1

flutter: 
  assets:
    - assets/
  uses-material-design: true