name: intro

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  appwrite_auth_kit: ^0.8.0
  components: { path: ../../components }
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true